In [1]:
import pandas as p

In [5]:
df = pd.DataFrame({
    "color" : ["Red","Green","Blue","Green","Red"],
    "Size"  : ["Small","Medium","Large","Medium","Small"],
    "City"  : ["Hyderabad","Delhi","Mumbai","Delhi","Chennai"],
    "Target": [10,20,15,25,12]
})
df

   color    Size       City  Target
0    Red   Small  Hyderabad      10
1  Green  Medium      Delhi      20
2   Blue   Large     Mumbai      15
3  Green  Medium      Delhi      25
4    Red   Small    Chennai      12

# Label Encoding

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
df["color_Label"] = LabelEncoder().fit_transform(df["color"])
df[["color", "color_Label"]]

   color  color_Label
0    Red            2
1  Green            1
2   Blue            0
3  Green            1
4    Red            2

# One-Hot Encoding

In [17]:
one_hot = pd.get_dummies(df["color"], prefix="color")
one_hot

   color_Blue  color_Green  color_Red
0       False        False       True
1       False         True      False
2        True        False      False
3       False         True      False
4       False        False       True

In [20]:
one_hot = pd.get_dummies(df, columns=["color"])
print(one_hot)

     Size       City  Target  color_Label  color_Blue  color_Green  color_Red
0   Small  Hyderabad      10            2       False        False       True
1  Medium      Delhi      20            1       False         True      False
2   Large     Mumbai      15            0        True        False      False
3  Medium      Delhi      25            1       False         True      False
4   Small    Chennai      12            2       False        False       True

# Ordinal Encoding

In [22]:
from sklearn.preprocessing import OrdinalEncoder

In [29]:
order = [["Small","Medium","Large"]]
df["Size_Ordinal"] = OrdinalEncoder(categories=order).fit_transform(df[["Size"]])

df[["Size", "Size_Ordinal"]]

     Size  Size_Ordinal
0   Small           0.0
1  Medium           1.0
2   Large           2.0
3  Medium           1.0
4   Small           0.0

# Target (Mean) Encoding

In [4]:
import pandas as pd
df = pd.DataFrame({
    "color" : ["Red","Green","Blue","Green","Red"],
    "Size"  : ["Small","Medium","Large","Medium","Small"],
    "City"  : ["Hyderabad","Delhi","Mumbai","Delhi","Chennai"],
    "Target": [10,20,15,25,12]
})
df

te = df.groupby("City")["Target"].mean()

df["City_Target_Enc"] = df["City"].map(te)
df[["City", "City_Target_Enc"]]

        City  City_Target_Enc
0  Hyderabad             10.0
1      Delhi             22.5
2     Mumbai             15.0
3      Delhi             22.5
4    Chennai             12.0

# Frequency Encoding

In [7]:
freq = df["City"].value_counts()

df["City_Target_Enc"] = df["City"].map(freq)
df[["City", "City_Target_Enc"]]

        City  City_Target_Enc
0  Hyderabad                1
1      Delhi                2
2     Mumbai                1
3      Delhi                2
4    Chennai                1

In [1]:
pip install category_encoders

Requirement already satisfied: category_encoders in c:\users\ponna\downloads\documents\downloads\lib\site-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in c:\users\ponna\downloads\documents\downloads\lib\site-packages (from category_encoders) (1.24.3)
Requirement already satisfied: pandas>=1.0.5 in c:\users\ponna\downloads\documents\downloads\lib\site-packages (from category_encoders) (2.0.3)
Requirement already satisfied: patsy>=0.5.1 in c:\users\ponna\downloads\documents\downloads\lib\site-packages (from category_encoders) (0.5.3)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\ponna\downloads\documents\downloads\lib\site-packages (from category_encoders) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in c:\users\ponna\downloads\documents\downloads\lib\site-packages (from category_encoders) (1.11.1)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\ponna\downloads\documents\downloads\lib\site-packages (from category_encoders) (0.14.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ponna\downloads\documents\downloads\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\ponna\downloads\documents\downloads\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\ponna\downloads\documents\downloads\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3)
Requirement already satisfied: six in c:\users\ponna\downloads\documents\downloads\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\ponna\downloads\documents\downloads\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\ponna\downloads\documents\downloads\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in c:\users\ponna\downloads\documents\downloads\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (23.1)
Note: you may need to restart the kernel to use updated packages.

# Binary Encoding

In [2]:
import category_encoders as ce

In [4]:
import pandas as pd
df = pd.DataFrame({
    "color" : ["Red","Green","Blue","Green","Red"],
    "Size"  : ["Small","Medium","Large","Medium","Small"],
    "City"  : ["Hyderabad","Delhi","Mumbai","Delhi","Chennai"],
    "Target": [10,20,15,25,12]
})
data_binary =  ce.BinaryEncoder(cols=["City"]).fit_transform(df["City"])
data_binary

   City_0  City_1  City_2
0       0       0       1
1       0       1       0
2       0       1       1
3       0       1       0
4       1       0       0

In [4]:
import pandas as pd
df = pd.DataFrame({
    "color" : ["Red","Green","Blue","Green","Red"],
    "Size"  : ["Small","Medium","Large","Medium","Small"],
    "City"  : ["Hyderabad","Delhi","Mumbai","Delhi","Chennai"],
    "Target": [10,20,15,25,12]
})

In [6]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(df[["City"]])
encoded_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out(["City"]))

In [7]:
encoded_df

   City_Chennai  City_Delhi  City_Hyderabad  City_Mumbai
0           0.0         0.0             1.0          0.0
1           0.0         1.0             0.0          0.0
2           0.0         0.0             0.0          1.0
3           0.0         1.0             0.0          0.0
4           1.0         0.0             0.0          0.0